<?xml version="1.0" encoding="utf-8"?><Database Name="CHTC" Class="ThuCungDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HVT\SQLEXPRESS;Initial Catalog=CHTC;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CHTCConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHUCVU" Member="CHUCVUs">
    <Type Name="CHUCVU">
      <Column Name="MACV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MOTACV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="CHUCVU_NHANVIEN" Member="NHANVIENs" ThisKey="MACV" OtherKey="CHUCVU" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.CTHOADONTHUCUNG" Member="CTHOADONTHUCUNGs">
    <Type Name="CTHOADONTHUCUNG">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONGMUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CTHOADONTHUCUNG" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="THUCUNG_CTHOADONTHUCUNG" Member="THUCUNG" ThisKey="MATC" OtherKey="MATC" Type="THUCUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIONG" Member="GIONGs">
    <Type Name="GIONG">
      <Column Name="MAGIONG" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENGIONG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MOTAG" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="GIONG_THUCUNG" Member="THUCUNGs" ThisKey="MAGIONG" OtherKey="MAGIONG" Type="THUCUNG" />
      <Association Name="LOAI_GIONG" Member="LOAI" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MAKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAKM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="HOADON_CTHOADONTHUCUNG" Member="CTHOADONTHUCUNGs" ThisKey="MAHD" OtherKey="MAHD" Type="CTHOADONTHUCUNG" />
      <Association Name="KHUYENMAI_HOADON" Member="KHUYENMAI" ThisKey="MAKM" OtherKey="MAKM" Type="KHUYENMAI" IsForeignKey="true" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MAKM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GIATRIKM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYBD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYKT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KHUYENMAI_HOADON" Member="HOADONs" ThisKey="MAKM" OtherKey="MAKM" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TAIKHOAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="MAKH" OtherKey="MAKH" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="CHUCVU" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="CHUCVU_NHANVIEN" Member="CHUCVU1" ThisKey="CHUCVU" OtherKey="MACV" Type="CHUCVU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI" Member="LOAIs">
    <Type Name="LOAI">
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="LOAI_GIONG" Member="GIONGs" ThisKey="MALOAI" OtherKey="MALOAI" Type="GIONG" />
    </Type>
  </Table>
  <Table Name="dbo.NCCGIONG" Member="NCCGIONGs">
    <Type Name="NCCGIONG">
      <Column Name="MANCC" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Association Name="NCCGIONG_THUCUNG" Member="THUCUNGs" ThisKey="MANCC" OtherKey="MANCC" Type="THUCUNG" />
    </Type>
  </Table>
  <Table Name="dbo.THUCUNG" Member="THUCUNGs">
    <Type Name="THUCUNG">
      <Column Name="MATC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAGIONG" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CANNANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ANH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="THUCUNG_CTHOADONTHUCUNG" Member="CTHOADONTHUCUNGs" ThisKey="MATC" OtherKey="MATC" Type="CTHOADONTHUCUNG" />
      <Association Name="GIONG_THUCUNG" Member="GIONG" ThisKey="MAGIONG" OtherKey="MAGIONG" Type="GIONG" IsForeignKey="true" />
      <Association Name="NCCGIONG_THUCUNG" Member="NCCGIONG" ThisKey="MANCC" OtherKey="MANCC" Type="NCCGIONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TK" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MK" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>